environment: dev
debug: false

search:
  provider: auto
  cascade_order: [serper, google, brave]
  default_options:
    lang: en
    geo: null
    max_results: 50

llm:
  provider: openai
  prompt_path: app/llm/prompts/rewrite_query.txt
  model: null
  temperature: 0.0
  timeout_seconds: 5.0

